import { NextRequest, NextResponse } from 'next/server'
import { getSettings } from '@/lib/settings-db'
import { researchTopic, scrapeUrl } from '@/lib/ai/scraper'

/**
 * AI Blog Scheduler API
 * Generates blog posts automatically based on schedule and topics
 */

interface BlogScheduleRequest {
  topic: string
  keywords?: string[]
  tone?: 'professional' | 'casual' | 'technical' | 'friendly'
  length?: 'short' | 'medium' | 'long'
  includeImages?: boolean
  research?: boolean
  sources?: string[]
}

interface GeneratedBlog {
  title: string
  content: string
  excerpt: string
  keywords: string[]
  seo: {
    title: string
    description: string
  }
  sources?: string[]
}

/**
 * Generate blog post using AI
 */
async function generateBlogPost(params: BlogScheduleRequest): Promise<GeneratedBlog> {
  const settings = await getSettings()
  
  if (!settings.ai?.enabled || !settings.ai?.autoBlog) {
    throw new Error('Auto-blog generation is not enabled')
  }

  const apiKey = process.env.AI_API_KEY || settings.ai?.apiKey
  const baseUrl = process.env.AI_BASE_URL || settings.ai?.baseUrl || 'https://api.openai.com/v1'
  const model = process.env.AI_MODEL || settings.ai?.model || 'gpt-4'

  if (!apiKey) {
    throw new Error('AI API key not configured')
  }

  const {
    topic,
    keywords = [],
    tone = 'professional',
    length = 'medium',
    includeImages = false,
    research = true,
    sources = []
  } = params

  // Research topic if enabled
  let researchContext = ''
  let researchSources: string[] = []

  if (research && sources.length === 0) {
    try {
      const researched = await researchTopic(topic, 3)
      researchContext = researched
        .map(r => `Source: ${r.title}\n${r.content.substring(0, 1000)}`)
        .join('\n\n')
      researchSources = researched.map(r => r.url)
    } catch (error) {
      console.error('Research failed, proceeding without:', error)
    }
  } else if (sources.length > 0) {
    try {
      const scraped = await Promise.all(
        sources.map(url => scrapeUrl(url, { maxContentLength: 1000 }))
      )
      researchContext = scraped
        .map(r => `Source: ${r.title}\n${r.content}`)
        .join('\n\n')
      researchSources = sources
    } catch (error) {
      console.error('Source scraping failed:', error)
    }
  }

  // Determine word count based on length
  const wordCounts = {
    short: '500-800',
    medium: '1000-1500',
    long: '2000-3000'
  }
  const targetWords = wordCounts[length]

  // Build prompt
  const keywordsText = keywords.length > 0 ? `Focus keywords: ${keywords.join(', ')}` : ''
  const researchText = researchContext ? `\nResearch material:\n${researchContext}` : ''

  const prompt = `Write a comprehensive blog post about: ${topic}

${keywordsText}
Tone: ${tone}
Target length: ${targetWords} words

${researchText}

Requirements:
1. Create an engaging, SEO-optimized blog post
2. Use proper headings (H2, H3) and formatting
3. Include an introduction, main content sections, and conclusion
4. Make it informative and valuable to readers
5. Naturally incorporate the focus keywords
6. Write in a ${tone} tone
${includeImages ? '7. Suggest 3-5 relevant images with descriptions' : ''}

Format the response as JSON with:
- title: Catchy blog post title
- content: Full blog post in markdown format
- excerpt: 2-3 sentence summary (150 chars max)
- keywords: Array of 5-10 relevant keywords
- seo: { title: "SEO title (60 chars)", description: "Meta description (160 chars)" }
${includeImages ? '- images: Array of { description: "image description", alt: "alt text" }' : ''}

Respond only with valid JSON.`

  // Call AI API
  const response = await fetch(`${baseUrl}/chat/completions`, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      model,
      messages: [
        {
          role: 'system',
          content: 'You are an expert content writer and blogger. Generate high-quality, SEO-optimized blog posts in JSON format.'
        },
        {
          role: 'user',
          content: prompt
        }
      ],
      temperature: 0.8,
      max_tokens: 4000
    })
  })

  if (!response.ok) {
    const error = await response.text()
    throw new Error(`AI API error: ${error}`)
  }

  const data = await response.json()
  const generatedContent = data.choices[0]?.message?.content

  if (!generatedContent) {
    throw new Error('No content generated by AI')
  }

  // Parse JSON response
  try {
    const jsonMatch = generatedContent.match(/\{[\s\S]*\}/)
    if (!jsonMatch) {
      throw new Error('No valid JSON found in response')
    }

    const blogData = JSON.parse(jsonMatch[0])

    return {
      title: blogData.title || topic,
      content: blogData.content || '',
      excerpt: blogData.excerpt || '',
      keywords: Array.isArray(blogData.keywords) ? blogData.keywords : keywords,
      seo: {
        title: blogData.seo?.title || blogData.title || topic,
        description: blogData.seo?.description || blogData.excerpt || ''
      },
      sources: researchSources.length > 0 ? researchSources : undefined
    }
  } catch (parseError) {
    console.error('Failed to parse AI response:', parseError)
    throw new Error('Failed to parse generated blog post')
  }
}

/**
 * POST /api/ai/blog-scheduler
 * Generate a blog post
 */
export async function POST(request: NextRequest) {
  try {
    const body: BlogScheduleRequest = await request.json()

    // Validate request
    if (!body.topic || body.topic.trim().length === 0) {
      return NextResponse.json(
        { success: false, error: 'Topic is required' },
        { status: 400 }
      )
    }

    console.log('Generating blog post:', {
      topic: body.topic,
      tone: body.tone || 'professional',
      length: body.length || 'medium'
    })

    // Generate blog post
    const blog = await generateBlogPost(body)

    console.log('Blog post generated:', {
      title: blog.title,
      contentLength: blog.content.length,
      keywordCount: blog.keywords.length
    })

    return NextResponse.json({
      success: true,
      blog
    })
  } catch (error) {
    console.error('Blog generation error:', error)
    const errorMessage = error instanceof Error ? error.message : 'Failed to generate blog post'
    
    return NextResponse.json(
      { success: false, error: errorMessage },
      { status: 500 }
    )
  }
}

/**
 * GET /api/ai/blog-scheduler
 * Check if auto-blog generation is available
 */
export async function GET() {
  try {
    const settings = await getSettings()
    
    const isAvailable = !!(
      settings.ai?.enabled &&
      settings.ai?.autoBlog &&
      (process.env.AI_API_KEY || settings.ai?.apiKey)
    )

    return NextResponse.json({
      available: isAvailable,
      enabled: settings.ai?.autoBlog || false,
      features: {
        research: true,
        seoOptimization: true,
        multipleFormats: true
      }
    })
  } catch (error) {
    console.error('Error checking blog scheduler availability:', error)
    return NextResponse.json(
      { available: false, enabled: false },
      { status: 500 }
    )
  }
}